import React from 'react'

const Waiver: React.FC<{}> = () => (
  <textarea
    className="vh-25 w-100 lh-title bg-light-gray ba b--light-gray br1 pa2"
    style={{ resize: 'none' }}
    readOnly
    value={`YOGA TEACHER AND LOCATION LIABILITY STUDENT WAIVER AGREEMENT
      I, the person registering above, understand that yoga includes physical movements as well as an opportunity for relaxation, stress re­education and relief of muscular tension. Participation in yoga class includes, but is not limited to, participation in meditation techniques, yogic breathing techniques, and performing various yoga postures. Yoga postures, or asanas, are designed to exercise every part of the body―stretching and toning the muscles and joints, the spine and the entire skeletal system. They also work on the internal organs, glands and nerves. Yoga incorporates sustained stretching to strengthen muscles and increase flexibility. Yoga is an individual experience.
      As is the case with any physical activity, the risk of injury, even serious or disabling, is always present and cannot be entirely eliminated. My signature acknowledges I understand that in yoga class I will progress at my own pace. If I experience any pain or discomfort, I will listen to my body, adjust the posture and ask for support from the yoga teacher (the “Teacher”). I will continue to breathe smoothly. If at any point I feel overexertion or fatigue, I will respect my body’s limitations and I will rest before continuing yoga practice.
      Yoga is not a substitute for medical attention, examination, diagnosis or treatment. Yoga is not recommended and is not safe under certain medical conditions. I affirm that I alone am responsible to decide whether to practice yoga.
      By signing my name below, I acknowledge that participation in yoga classes exposes me to a possible risk of personal injury. I am fully aware of this risk. I hereby consent to receive medical treatment that may be deemed advisable in the event of injury, accident and/or illness during any yoga class.
      I hereby take action for myself, my executors, administrators, heirs, next of kin, successors and assigns as follows: I (a) irrevocably WAIVE, RELEASE AND DISCHARGE FROM ANY AND ALL LIABILITY for my death, disability, personal injury, property damage, property theft or actions of any kind which hereafter may occur to me, including my traveling to and from yoga classes, Annie Hayes Wellness, Anne Krohn, or any other yoga teacher teaching for AHW, and yoga class location, who is hosting these classes and where sessions are being held, and each of their directors, officers, employees, volunteers, representatives and agents; and (b) INDEMNIFY, HOLD HARMLESS AND AGREE NOT TO SUE the entities or persons mentioned in this paragraph as to any and all liabilities or claims made as a result of participation in the yoga classes, whether caused by the negligence of releasees or otherwise.
      My signature further acknowledges that I shall not now or at any time in the future bring any legal action against Teacher and/or yoga class location and that this waiver is binding on me, my heirs, my spouse, my children, my legal representatives, my successors and my assigns. My signature verifies that I am physically fit to participate in yoga classes and a licensed medical doctor has verified my physical condition for participation in this type of class.
      If I am pregnant or become pregnant or am post­natal, my signature verifies that I am participating in yoga classes with my doctor’s full approval. I realize that I am participating in yoga classes at my own risk.
      The Student Waiver Agreement shall be construed broadly to provide a release and waiver to the maximum extent permissible under applicable law. I acknowledge that this Student Waiver Agreement form will be used by the persons or entities being released in the yoga classes and that it will govern my actions and responsibilities in said classes.
      I hereby certify that I have read this document; and, I understand its content. I am aware that this is a release of liability as well as a contract and I sign it of my own free will.`}
  ></textarea>
)

export default Waiver
